packages:
  - src/ModInstaller.Native.TypeScript
  - src/ModInstaller.IPC.TypeScript

catalog:
  7zip-bin: ^5.2.0
  '@types/node': ^22.0.0
  node-7z: ^3.0.0
  node-addon-api: 8.5.0
  node-gyp: 10.0.0
  node-stream-zip: ^1.15.0
  ts-loader: ^9.5.1
  ts-node: ^10.9.1
  typescript: ^5.0.0
  vitest: ^4.1.1
  vortex-api: Nexus-Mods/vortex-api
  webpack: ^5.95.0
  webpack-cli: ^5.1.4
  winapi-bindings: Nexus-Mods/node-winapi-bindings
